In [2]:
import numpy as np 
import pandas as pd 

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/mervebzn/hospitaldataset/LUTH_Hospital_Enhanced_Dataset.xlsx

# Initial Exploration

In [3]:
df= pd.read_excel("/kaggle/input/datasets/mervebzn/hospitaldataset/LUTH_Hospital_Enhanced_Dataset.xlsx")

df.shape
df.head()

,Patient ID,Name,Age,Gender,Department,Diagnosis,Treatment,Doctor,Visit Date,Cost (Naira),Ward,Payment Method,Outcome,Follow-Up Required,Satisfaction Score (1-5),Admission Time,Discharge Time
0,LUTH-1000,Patient_1,44,Female,Oncology,Malaria,Surgery,Dr. Obi,2024-02-21,243721.97,Ward D,Cash,Deceased,No,4,2024-02-21 13:13:00,2024-03-02 13:13:00
1,LUTH-1001,Patient_2,51,Male,Neurology,Cancer,Referral,Dr. Bello,2024-11-22,150679.18,Ward C,Insurance,Under Observation,No,1,2024-11-22 17:22:00,2024-12-05 17:22:00
2,LUTH-1002,Patient_3,20,Female,Cardiology,Fracture,Physiotherapy,Dr. Johnson,2024-09-18,97198.81,Ward E,Cash,Deceased,Yes,4,2024-09-18 10:34:00,2024-10-02 10:34:00
3,LUTH-1003,Patient_4,73,Male,Orthopedics,Infection,Physiotherapy,Dr. Okafor,2024-09-14,178102.61,Ward E,Card,Recovered,No,3,2024-09-14 11:34:00,2024-09-25 11:34:00
4,LUTH-1004,Patient_5,78,Male,Pediatrics,Fracture,Surgery,Dr. Musa,2024-07-08,201972.05,Ward E,Insurance,Referred,No,4,2024-07-08 14:52:00,2024-07-23 14:52:00

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient ID                500 non-null    object
 1   Name                      500 non-null    object
 2   Age                       500 non-null    int64
 3   Gender                    500 non-null    object
 4   Department                500 non-null    object
 5   Diagnosis                 500 non-null    object
 6   Treatment                 500 non-null    object
 7   Doctor                    500 non-null    object
 8   Visit Date                500 non-null    datetime64[ns]
 9   Cost (Naira)              500 non-null    float64
 10  Ward                      500 non-null    object
 11  Payment Method            500 non-null    object
 12  Outcome                   500 non-null    object
 13  Follow-Up Required        500 non-null    object
 14  Satisfaction Score (1-5)  500 non-null    int64
 15  Admission Time            500 non-null    object
 16  Discharge Time            500 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 66.5+ KB

In [5]:
# Missing values check
df.isnull().sum()

Patient ID                  0
Name                        0
Age                         0
Gender                      0
Department                  0
Diagnosis                   0
Treatment                   0
Doctor                      0
Visit Date                  0
Cost (Naira)                0
Ward                        0
Payment Method              0
Outcome                     0
Follow-Up Required          0
Satisfaction Score (1-5)    0
Admission Time              0
Discharge Time              0
dtype: int64

In [6]:
# Duplicate
df.duplicated().sum()

np.int64(0)

In [7]:
df["Patient ID"].duplicated().sum()

np.int64(0)

# Data Cleaning

In [8]:
# Conver data types
df['Visit Date'] = pd.to_datetime(df['Visit Date'])
df['Admission Time'] = pd.to_datetime(df['Admission Time'])
df['Discharge Time'] = pd.to_datetime(df['Discharge Time'])

df['Patient ID'] = df['Patient ID'].astype(str)

In [9]:
cat_cols = ["Gender", "Department", "Diagnosis", "Treatment", "Doctor",
            "Ward", "Payment Method", "Outcome", "Follow-Up Required"]

for col in cat_cols:
    df[col]= df[col].astype(str).str.strip()
    df[col] = df[col].astype('category')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient ID                500 non-null    object
 1   Name                      500 non-null    object
 2   Age                       500 non-null    int64
 3   Gender                    500 non-null    category
 4   Department                500 non-null    category
 5   Diagnosis                 500 non-null    category
 6   Treatment                 500 non-null    category
 7   Doctor                    500 non-null    category
 8   Visit Date                500 non-null    datetime64[ns]
 9   Cost (Naira)              500 non-null    float64
 10  Ward                      500 non-null    category
 11  Payment Method            500 non-null    category
 12  Outcome                   500 non-null    category
 13  Follow-Up Required        500 non-null    category
 14  Satisfaction Score (1-5)  500 non-null    int64
 15  Admission Time            500 non-null    datetime64[ns]
 16  Discharge Time            500 non-null    datetime64[ns]
dtypes: category(9), datetime64[ns](3), float64(1), int64(2), object(2)
memory usage: 37.8+ KB

In [10]:
# Standardization check
for col in cat_cols:
    print(col, '-> \n', df[col].unique().tolist())

Gender ->
 ['Female', 'Male']
Department ->
 ['Oncology', 'Neurology', 'Cardiology', 'Orthopedics', 'Pediatrics', 'Emergency', 'General Surgery']
Diagnosis ->
 ['Malaria', 'Cancer', 'Fracture', 'Infection', 'Hypertension', 'Diabetes', 'Stroke']
Treatment ->
 ['Surgery', 'Referral', 'Physiotherapy', 'Observation', 'Chemotherapy', 'Medication']
Doctor ->
 ['Dr. Obi', 'Dr. Bello', 'Dr. Johnson', 'Dr. Okafor', 'Dr. Musa', 'Dr. Ahmed', 'Dr. Adeyemi']
Ward ->
 ['Ward D', 'Ward C', 'Ward E', 'Ward A', 'Ward B']
Payment Method ->
 ['Cash', 'Insurance', 'Card']
Outcome ->
 ['Deceased', 'Under Observation', 'Recovered', 'Referred']
Follow-Up Required ->
 ['No', 'Yes']

In [11]:
# Unrealistic value check
print(df['Age'].describe())
print('\nAge <0  or >120:', ((df['Age']<0) | (df['Age']>120)).sum())

count    500.000000
mean      45.196000
std       25.939377
min        1.000000
25%       23.000000
50%       44.500000
75%       68.000000
max       90.000000
Name: Age, dtype: float64

Age <0  or >120: 0

In [12]:
print(df['Cost (Naira)'].describe())
print('Cost <= 0:', (df['Cost (Naira)'] <=0).sum())

count       500.000000
mean     132347.486460
std       68992.844624
min       10211.400000
25%       75035.492500
50%      130198.560000
75%      188105.530000
max      249943.290000
Name: Cost (Naira), dtype: float64
Cost <= 0: 0

In [13]:
print(df["Satisfaction Score (1-5)"].describe())
print('Unrealistick satisfaction:', ((df['Satisfaction Score (1-5)'] <1) | (df['Satisfaction Score (1-5)']>5)).sum())

count    500.000000
mean       2.986000
std        1.390565
min        1.000000
25%        2.000000
50%        3.000000
75%        4.000000
max        5.000000
Name: Satisfaction Score (1-5), dtype: float64
Unrealistick satisfaction: 0

In [14]:
# Logical date checks
print('Discharge < Admission :', (df["Discharge Time"] < df["Admission Time"]).sum())
print('Visit Date != Admission Date :', (df['Visit Date'].dt.date != df['Admission Time'].dt.date).sum())

Discharge < Admission : 0
Visit Date != Admission Date : 0

In [15]:
# Outlier
for col in ['Age', 'Cost (Naira)']:
    Q1, Q3 = df[col].quantile(0.25), df[col].quantile(0.75)
    IQR = Q3-Q1
    lower, upper = Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
    outliers = df[(df[col]< lower) | (df[col]> upper)]
    print(f"{col}: {len(outliers)} outliers (lower: {lower:.1f}, upper: {upper:.1f})")

Age: 0 outliers (lower: -44.5, upper: 135.5)
Cost (Naira): 0 outliers (lower: -94569.6, upper: 357710.6)

In [16]:
print(df.info())
print(df.describe(include="all").T)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient ID                500 non-null    object
 1   Name                      500 non-null    object
 2   Age                       500 non-null    int64
 3   Gender                    500 non-null    category
 4   Department                500 non-null    category
 5   Diagnosis                 500 non-null    category
 6   Treatment                 500 non-null    category
 7   Doctor                    500 non-null    category
 8   Visit Date                500 non-null    datetime64[ns]
 9   Cost (Naira)              500 non-null    float64
 10  Ward                      500 non-null    category
 11  Payment Method            500 non-null    category
 12  Outcome                   500 non-null    category
 13  Follow-Up Required        500 non-null    category
 14  Satisfaction Score (1-5)  500 non-null    int64
 15  Admission Time            500 non-null    datetime64[ns]
 16  Discharge Time            500 non-null    datetime64[ns]
dtypes: category(9), datetime64[ns](3), float64(1), int64(2), object(2)
memory usage: 37.8+ KB
None
                          count unique            top freq  \
Patient ID                  500    500      LUTH-1499    1
Name                        500    500    Patient_500    1
Age                       500.0    NaN            NaN  NaN
Gender                      500      2         Female  259
Department                  500      7    Orthopedics   80
Diagnosis                   500      7       Diabetes   78
Treatment                   500      6  Physiotherapy   92
Doctor                      500      7    Dr. Adeyemi   83
Visit Date                  500    NaN            NaN  NaN
Cost (Naira)              500.0    NaN            NaN  NaN
Ward                        500      5         Ward A  111
Payment Method              500      3           Card  171
Outcome                     500      4       Deceased  138
Follow-Up Required          500      2            Yes  251
Satisfaction Score (1-5)  500.0    NaN            NaN  NaN
Admission Time              500    NaN            NaN  NaN
Discharge Time              500    NaN            NaN  NaN

                                                   mean                  min  \
Patient ID                                          NaN                  NaN
Name                                                NaN                  NaN
Age                                              45.196                  1.0
Gender                                              NaN                  NaN
Department                                          NaN                  NaN
Diagnosis                                           NaN                  NaN
Treatment                                           NaN                  NaN
Doctor                                              NaN                  NaN
Visit Date                   2024-06-27 01:14:52.800000  2024-01-01 00:00:00
Cost (Naira)                               132347.48646              10211.4
Ward                                                NaN                  NaN
Payment Method                                      NaN                  NaN
Outcome                                             NaN                  NaN
Follow-Up Required                                  NaN                  NaN
Satisfaction Score (1-5)                          2.986                  1.0
Admission Time            2024-06-27 13:36:00.600000256  2024-01-01 16:02:00
Discharge Time            2024-07-05 14:04:48.600000256  2024-01-07 16:02:00

                                          25%                  50%  \
Patient ID                                NaN                  NaN
Name                                      NaN                  NaN
Age                                      23.0                 44.5
Gender                                    NaN                  NaN
Department                                NaN                  NaN
Diagnosis                                 NaN                  NaN
Treatment                                 NaN                  NaN
Doctor                                    NaN                  NaN
Visit Date                2024-03-28 12:00:00  2024-06-26 12:00:00
Cost (Naira)                       75035.4925            130198.56
Ward                                      NaN                  NaN
Payment Method                            NaN                  NaN
Outcome                                   NaN                  NaN
Follow-Up Required                        NaN                  NaN
Satisfaction Score (1-5)                  2.0                  3.0
Admission Time            2024-03-28 20:50:45  2024-06-26 22:41:00
Discharge Time            2024-04-05 00:13:45  2024-07-04 12:02:00

                                          75%                  max  \
Patient ID                                NaN                  NaN
Name                                      NaN                  NaN
Age                                      68.0                 90.0
Gender                                    NaN                  NaN
Department                                NaN                  NaN
Diagnosis                                 NaN                  NaN
Treatment                                 NaN                  NaN
Doctor                                    NaN                  NaN
Visit Date                2024-09-27 06:00:00  2024-12-31 00:00:00
Cost (Naira)                        188105.53            249943.29
Ward                                      NaN                  NaN
Payment Method                            NaN                  NaN
Outcome                                   NaN                  NaN
Follow-Up Required                        NaN                  NaN
Satisfaction Score (1-5)                  4.0                  5.0
Admission Time            2024-09-27 14:00:15  2024-12-31 09:58:00
Discharge Time            2024-10-05 04:57:45  2025-01-09 16:55:00

                                   std
Patient ID                         NaN
Name                               NaN
Age                          25.939377
Gender                             NaN
Department                         NaN
Diagnosis                          NaN
Treatment                          NaN
Doctor                             NaN
Visit Date                         NaN
Cost (Naira)              68992.844624
Ward                               NaN
Payment Method                     NaN
Outcome                            NaN
Follow-Up Required                 NaN
Satisfaction Score (1-5)      1.390565
Admission Time                     NaN
Discharge Time                     NaN

# CALCULATED COLUMNS

In [17]:
# Length of Stay
df['LOS_Days'] = (df['Discharge Time'] - df['Admission Time']).dt.days

print(df['LOS_Days'])

0      10
1      13
2      14
3      11
4      15
       ..
495     1
496     3
497     8
498     8
499     2
Name: LOS_Days, Length: 500, dtype: int64

In [18]:
# Cost per day
effective_days = np.maximum(df['LOS_Days'],1)
df['Cost_per_day']= (df['Cost (Naira)']/effective_days).round(2)
print(df[["Cost (Naira)", "LOS_Days", "Cost_per_day"]].head())

   Cost (Naira)  LOS_Days  Cost_per_day
0     243721.97        10      24372.20
1     150679.18        13      11590.71
2      97198.81        14       6942.77
3     178102.61        11      16191.15
4     201972.05        15      13464.80

In [19]:
print(
    df.groupby(["Department", "Ward"], observed=True)["Cost_per_day"]
    .mean()
    .round(2)
)

Department       Ward
Cardiology       Ward A    21930.41
                 Ward B    27030.12
                 Ward C    26142.65
                 Ward D    33633.87
                 Ward E    35895.01
Emergency        Ward A    38047.35
                 Ward B    29402.29
                 Ward C    23531.73
                 Ward D    33916.51
                 Ward E    28205.66
General Surgery  Ward A    34893.67
                 Ward B    15120.61
                 Ward C    27250.22
                 Ward D    56494.04
                 Ward E    33336.77
Neurology        Ward A    26176.09
                 Ward B    30572.05
                 Ward C    19704.36
                 Ward D    18384.85
                 Ward E    32154.78
Oncology         Ward A    30441.62
                 Ward B    29385.76
                 Ward C    29108.02
                 Ward D    22874.33
                 Ward E    19418.72
Orthopedics      Ward A    50019.11
                 Ward B    28219.40
                 Ward C    26654.21
                 Ward D    29479.80
                 Ward E    26378.52
Pediatrics       Ward A    19479.62
                 Ward B    30877.27
                 Ward C    17353.49
                 Ward D    41885.40
                 Ward E    32401.52
Name: Cost_per_day, dtype: float64

In [20]:
# Age group
bins = [0,12,18,35,60,120]
labels = ["Child (0-12)", "Teen (13-18)", "Young Adult (19-35)", "Adult (36-60)", "Senior (60+)"]
df['Age_Group'] = pd.cut(df['Age'], bins= bins, labels=labels)

df['Age_Group']

0            Adult (36-60)
1            Adult (36-60)
2      Young Adult (19-35)
3             Senior (60+)
4             Senior (60+)
              ...
495           Senior (60+)
496           Senior (60+)
497    Young Adult (19-35)
498          Adult (36-60)
499           Senior (60+)
Name: Age_Group, Length: 500, dtype: category
Categories (5, object): ['Child (0-12)' < 'Teen (13-18)' < 'Young Adult (19-35)' < 'Adult (36-60)' < 'Senior (60+)']

In [21]:
# Visit Month / Quarter / Weekday
df['Visit_Month'] = df['Visit Date'].dt.month_name()
df['Visit_Quarter'] = df['Visit Date'].dt.quarter
df['Visit_Weekday'] = df['Visit Date'].dt.day_name()

In [22]:
# Is_Recovered / Is_Deceased flag 
df['Is_Recovered'] = (df['Outcome']=='Recovered').astype(int)
df["Is_Deceased"] = (df["Outcome"] == "Deceased").astype(int)
df['Is_FollowUp'] = (df['Follow-Up Required'] == 'Yes').astype(int)

In [23]:
df['Is_FollowUp']

0      0
1      0
2      1
3      0
4      0
      ..
495    1
496    1
497    1
498    1
499    0
Name: Is_FollowUp, Length: 500, dtype: int64

In [24]:
df.to_csv("LUTH_Hospital_Cleaned.csv", index=False)

## Doctor Dimension

In [27]:
doctor_dim = df.groupby(['Doctor','Department'], observed=True).agg(
    Total_Patients = ('Patient ID', 'count'),
    Avg_Satisfaction=('Satisfaction Score (1-5)', 'mean'),
    Recovery_Rate= ('Is_Recovered', 'mean'),
    Avg_LOS_Days = ('LOS_Days', 'mean')
).round(2).reset_index()

doctor_dim

,Doctor,Department,Total_Patients,Avg_Satisfaction,Recovery_Rate,Avg_LOS_Days
0,Dr. Adeyemi,Cardiology,7,2.86,0.43,8.29
1,Dr. Adeyemi,Emergency,14,2.93,0.36,6.14
2,Dr. Adeyemi,General Surgery,14,2.79,0.36,7.79
3,Dr. Adeyemi,Neurology,11,3.27,0.18,8.18
4,Dr. Adeyemi,Oncology,11,3.36,0.27,8.09
5,Dr. Adeyemi,Orthopedics,16,3.19,0.19,7.81
6,Dr. Adeyemi,Pediatrics,10,2.90,0.30,10.50
7,Dr. Ahmed,Cardiology,17,3.12,0.18,6.06
8,Dr. Ahmed,Emergency,12,3.25,0.17,7.58
9,Dr. Ahmed,General Surgery,10,3.40,0.30,9.10
10,Dr. Ahmed,Neurology,20,2.80,0.30,7.70
11,Dr. Ahmed,Oncology,8,2.75,0.25,5.88
12,Dr. Ahmed,Orthopedics,7,2.14,0.14,7.43
13,Dr. Ahmed,Pediatrics,8,3.75,0.25,10.50
14,Dr. Bello,Cardiology,14,3.36,0.07,7.00
15,Dr. Bello,Emergency,5,3.00,0.40,8.00
16,Dr. Bello,General Surgery,11,2.91,0.09,5.82
17,Dr. Bello,Neurology,7,3.14,0.57,9.29
18,Dr. Bello,Oncology,10,3.10,0.10,8.50
19,Dr. Bello,Orthopedics,10,2.80,0.20,7.90
20,Dr. Bello,Pediatrics,10,3.00,0.10,6.90
21,Dr. Johnson,Cardiology,10,3.00,0.00,9.10
22,Dr. Johnson,Emergency,12,2.50,0.00,7.83
23,Dr. Johnson,General Surgery,7,2.43,0.43,7.43
24,Dr. Johnson,Neurology,11,3.36,0.55,8.27
25,Dr. Johnson,Oncology,7,3.00,0.14,5.43
26,Dr. Johnson,Orthopedics,9,2.44,0.22,10.00
27,Dr. Johnson,Pediatrics,10,2.40,0.10,8.40
28,Dr. Musa,Cardiology,3,3.67,0.33,4.67
29,Dr. Musa,Emergency,14,2.93,0.29,8.00
30,Dr. Musa,General Surgery,4,2.50,0.00,7.00
31,Dr. Musa,Neurology,13,2.46,0.15,7.77
32,Dr. Musa,Oncology,13,3.15,0.23,10.77
33,Dr. Musa,Orthopedics,11,2.82,0.45,6.82
34,Dr. Musa,Pediatrics,16,3.56,0.12,8.75
35,Dr. Obi,Cardiology,5,2.60,0.40,6.80
36,Dr. Obi,Emergency,7,2.57,0.00,7.43
37,Dr. Obi,General Surgery,7,3.57,0.29,9.43
38,Dr. Obi,Neurology,9,3.56,0.44,9.22
39,Dr. Obi,Oncology,8,2.75,0.25,10.12
40,Dr. Obi,Orthopedics,16,2.56,0.38,6.75
41,Dr. Obi,Pediatrics,14,2.71,0.29,8.50
42,Dr. Okafor,Cardiology,16,3.06,0.31,8.56
43,Dr. Okafor,Emergency,8,3.00,0.12,10.00
44,Dr. Okafor,General Surgery,6,2.50,0.17,8.33
45,Dr. Okafor,Neurology,7,3.57,0.43,8.71
46,Dr. Okafor,Oncology,10,2.90,0.30,9.80
47,Dr. Okafor,Orthopedics,11,3.64,0.18,7.45
48,Dr. Okafor,Pediatrics,4,2.75,0.00,6.25

In [28]:
doctor_dim.to_csv("Doctor_Dimension.csv", index=False)